##Sample Data
#' @title Sample Student Performance Dataset
#' @description
#' A built-in dataset of student performance records.
#'
#' @docType data
#' @keywords datasets
#' @name student_data
#'
#' @format A data frame with 6 rows and 7 variables:
#' \describe{
#'   \item{Date}{Date of the assessment}
#'   \item{Subject}{Course subject}
#'   \item{Category}{Assignment type}
#'   \item{Score}{Points earned}
#'   \item{Total}{Maximum points}
#'   \item{StudyHours}{Hours spent studying}
#'   \item{Semester}{Semester identifier}
#' }
#' @source Generated by data-raw/student_data.R
#' @examples
#' data(student_data)
#' head(student_data)
"student_data"
